version: 2
jobs:
  build:

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt install make
      - run:
          name: Build postgres and redis
          command: docker-compose -f build/dev/docker-compose.yml up -d --build db redis

      - run:
          name: Build web, celery and celery beat
          command: docker-compose -f build/dev/docker-compose.yml up -d --build web celery celery beat

      run:
        name: Run tests
        command: docker exec -ti dev_web_1 pytest




workflows:
  version: 2
  build:
    jobs:
      - build